# Site settings
course_name: From Lab To Fulfillment
course_description: "From Lab 2 Fulfillment (FL2F) is a purpose-driven workshop that teaches women in science, engineering, technology, and math (STEM) and Medicine how to transform their research & discoveries into products and companies.

From Lab 2 Fulfillment was created by Dr. Yadid-Pecht to guide women in STEM and Medicine towards commercialization. Small interactive sessions alongside one-on-one coaching cultivate a supportive space to ideate and pivot research into businesses. The process that Dr. Yadid-Pecht has designed helps women in STEM and Medicine make their scientific innovations more impactful by showing them how to overcome hurdles, find supporters, and build their strategic plans and alliances."
course_semester: "Winter 2022"

baseurl: "/FL2F" # the subpath of your site, e.g. /blog/
url: "http://Taichi-Pink.github.io/" # the base hostname & protocol for your site

schoolname: ""
schoolurl: "https://www.fl2f.ca/"
twitter_username: from-lab-to-fulfillment

address: |
    University of Calgary, 2500 University Dr NW
    Calgary
    Canada

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

theme: jekyll-theme-architect
